# [file name]: pdf_generator.py
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from io import BytesIO
import base64
from datetime import datetime
from database import Database
import traceback

class PDFGenerator:
    @staticmethod
    def generate_leave_report(leave_data, report_type="monthly_summary", admin_name="Administrator"):
        """Generate PDF report for leaves"""
        try:
            buffer = BytesIO()
            
            # Create PDF document
            doc = SimpleDocTemplate(buffer, pagesize=letter)
            elements = []
            styles = getSampleStyleSheet()
            
            # Custom styles
            title_style = ParagraphStyle(
                'CustomTitle',
                parent=styles['Heading1'],
                fontSize=16,
                alignment=1,  # Center alignment
                spaceAfter=30,
                textColor=colors.HexColor('#dc3545')  # VIT Red
            )
            
            subtitle_style = ParagraphStyle(
                'CustomSubtitle',
                parent=styles['Heading2'],
                fontSize=12,
                alignment=1,
                spaceAfter=20,
                textColor=colors.HexColor('#333333')
            )
            
            normal_style = styles['Normal']
            
            # Title
            elements.append(Paragraph("VIT LEAVE MANAGEMENT SYSTEM", title_style))
            elements.append(Paragraph("LEAVE REPORT", subtitle_style))
            
            # Report details
            elements.append(Paragraph(f"Report Type: {report_type.replace('_', ' ').title()}", normal_style))
            elements.append(Paragraph(f"Generated On: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", normal_style))
            elements.append(Paragraph(f"Generated By: {admin_name}", normal_style))
            
            elements.append(Spacer(1, 20))
            
            # Summary section
            if report_type == "monthly_summary":
                elements.append(Paragraph("Monthly Leave Summary", styles['Heading2']))
                
                # Create summary table
                summary_data = [
                    ['Month', 'Total Leaves', 'Approved', 'Rejected', 'Pending', 'Suspicious']
                ]
                
                # Add data rows
                for month_data in leave_data.get('monthly_summary', []):
                    summary_data.append([
                        month_data.get('month', 'N/A'),
                        str(month_data.get('total', 0)),
                        str(month_data.get('approved', 0)),
                        str(month_data.get('rejected', 0)),
                        str(month_data.get('pending', 0)),
                        str(month_data.get('suspicious', 0))
                    ])
                
                # Create table
                summary_table = Table(summary_data, colWidths=[1.2*inch, 1*inch, 1*inch, 1*inch, 1*inch, 1.2*inch])
                summary_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#dc3545')),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                    ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, 0), 10),
                    ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                    ('BACKGROUND', (0, 1), (-1, -1), colors.white),
                    ('GRID', (0, 0), (-1, -1), 1, colors.grey),
                    ('FONTSIZE', (0, 1), (-1, -1), 9),
                ]))
                
                elements.append(summary_table)
            
            elif report_type == "leave_statistics":
                elements.append(Paragraph("Detailed Leave Statistics", styles['Heading2']))
                
                if leave_data.get('leaves'):
                    # Create detailed leaves table
                    leaves_data = [['ID', 'Student', 'Type', 'From', 'To', 'Status', 'Proctor']]
                    
                    for leave in leave_data['leaves'][:50]:  # Limit to 50 rows for PDF
                        leaves_data.append([
                            str(leave.get('leave_id', '')),
                            leave.get('student_name', '')[:20],
                            leave.get('leave_type', ''),
                            leave.get('from_date', '').strftime('%Y-%m-%d') if leave.get('from_date') else '',
                            leave.get('to_date', '').strftime('%Y-%m-%d') if leave.get('to_date') else '',
                            leave.get('status', ''),
                            leave.get('proctor_name', '')[:15]
                        ])
                    
                    leaves_table = Table(leaves_data, colWidths=[0.5*inch, 1.5*inch, 0.8*inch, 1*inch, 1*inch, 1*inch, 1.2*inch])
                    leaves_table.setStyle(TableStyle([
                        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#007bff')),
                        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                        ('FONTSIZE', (0, 0), (-1, 0), 9),
                        ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
                        ('BACKGROUND', (0, 1), (-1, -1), colors.white),
                        ('GRID', (0, 0), (-1, -1), 1, colors.grey),
                        ('FONTSIZE', (0, 1), (-1, -1), 8),
                        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8f9fa')]),
                    ]))
                    
                    elements.append(leaves_table)
            
            elif report_type == "user_activity":
                elements.append(Paragraph("User Activity Report", styles['Heading2']))
                
                # Add user statistics
                if leave_data.get('user_stats'):
                    user_stats = leave_data['user_stats']
                    
                    stats_data = [
                        ['Metric', 'Count'],
                        ['Total Students', str(user_stats.get('total_students', 0))],
                        ['Active Students (30 days)', str(user_stats.get('active_students', 0))],
                        ['Total Proctors', str(user_stats.get('total_proctors', 0))],
                        ['Total Supervisors', str(user_stats.get('total_supervisors', 0))],
                        ['Avg Leaves per Student', f"{user_stats.get('avg_leaves_per_student', 0):.2f}"],
                        ['Most Active Proctor', user_stats.get('most_active_proctor', 'N/A')],
                        ['Most Active Block', user_stats.get('most_active_block', 'N/A')]
                    ]
                    
                    stats_table = Table(stats_data, colWidths=[2*inch, 2*inch])
                    stats_table.setStyle(TableStyle([
                        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#28a745')),
                        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                        ('BACKGROUND', (0, 1), (-1, -1), colors.white),
                        ('GRID', (0, 0), (-1, -1), 1, colors.grey),
                    ]))
                    
                    elements.append(stats_table)
            
            # Footer
            elements.append(Spacer(1, 30))
            elements.append(Paragraph("This is an official report generated by VIT Leave Management System", 
                                     ParagraphStyle('Footer', parent=normal_style, fontSize=8, alignment=1)))
            elements.append(Paragraph(f"Page 1 of 1 | Report ID: {datetime.now().strftime('%Y%m%d%H%M%S')}", 
                                     ParagraphStyle('Footer', parent=normal_style, fontSize=8, alignment=1)))
            
            # Build PDF
            doc.build(elements)
            
            # Get PDF data
            pdf_data = buffer.getvalue()
            buffer.close()
            
            # Encode to base64 for download
            pdf_base64 = base64.b64encode(pdf_data).decode('utf-8')
            
            return pdf_base64
        
        except Exception as e:
            print(f"Error generating PDF report: {e}")
            traceback.print_exc()
            return None
    
    @staticmethod
    def generate_slip_pdf(slip_data):
        """Generate PDF slip for leave verification"""
        try:
            buffer = BytesIO()
            
            # Create PDF document
            doc = SimpleDocTemplate(buffer, pagesize=(6*inch, 4*inch))  # Smaller size for slip
            elements = []
            styles = getSampleStyleSheet()
            
            # Custom styles for slip
            header_style = ParagraphStyle(
                'SlipHeader',
                parent=styles['Heading1'],
                fontSize=14,
                alignment=1,
                spaceAfter=10,
                textColor=colors.HexColor('#dc3545')
            )
            
            # Header
            elements.append(Paragraph("VIT LEAVE SLIP", header_style))
            
            # Student Information
            elements.append(Paragraph("STUDENT INFORMATION", styles['Heading2']))
            
            student_info = f"""
            <b>Name:</b> {slip_data.get('student_name', 'N/A')}<br/>
            <b>Registration No:</b> {slip_data.get('reg_number', 'N/A')}<br/>
            <b>Hostel Block:</b> {slip_data.get('hostel_block', 'N/A')}<br/>
            <b>Room No:</b> {slip_data.get('room_number', 'N/A')}<br/>
            """
            elements.append(Paragraph(student_info, styles['Normal']))
            
            elements.append(Spacer(1, 10))
            
            # Leave Details
            elements.append(Paragraph("LEAVE DETAILS", styles['Heading2']))
            
            leave_info = f"""
            <b>From:</b> {slip_data.get('from_date', 'N/A')} at {slip_data.get('from_time', 'N/A')}<br/>
            <b>To:</b> {slip_data.get('to_date', 'N/A')} at {slip_data.get('to_time', 'N/A')}<br/>
            <b>Destination:</b> {slip_data.get('destination', 'Not specified')}<br/>
            <b>Proctor:</b> {slip_data.get('proctor_name', 'N/A')}<br/>
            """
            elements.append(Paragraph(leave_info, styles['Normal']))
            
            elements.append(Spacer(1, 10))
            
            # Verification Details
            elements.append(Paragraph("VERIFICATION", styles['Heading2']))
            
            verify_info = f"""
            <b>Verified By:</b> {slip_data.get('supervisor_name', 'N/A')}<br/>
            <b>Verified At:</b> {slip_data.get('verified_at', 'N/A')}<br/>
            <b>Status:</b> <font color="green"><b>APPROVED</b></font><br/>
            """
            elements.append(Paragraph(verify_info, styles['Normal']))
            
            elements.append(Spacer(1, 20))
            
            # Disclaimer
            elements.append(Paragraph(
                "This slip must be presented when leaving and returning to campus.",
                ParagraphStyle('Disclaimer', parent=styles['Normal'], fontSize=8, alignment=1)
            ))
            
            elements.append(Paragraph(
                f"Slip ID: {datetime.now().strftime('%Y%m%d%H%M%S')}",
                ParagraphStyle('SlipID', parent=styles['Normal'], fontSize=8, alignment=1)
            ))
            
            # Build PDF
            doc.build(elements)
            
            # Get PDF data
            pdf_data = buffer.getvalue()
            buffer.close()
            
            return pdf_data
        
        except Exception as e:
            print(f"Error generating PDF slip: {e}")
            traceback.print_exc()
            return None

class ReportData:
    @staticmethod
    def get_monthly_summary():
        """Get monthly summary data for reports"""
        db = Database()
        connection = db.get_connection()
        try:
            if not connection:
                return []
            
            with connection.cursor() as cursor:
                # Get data for last 6 months
                cursor.execute("""
                    SELECT 
                        DATE_FORMAT(applied_at, '%Y-%m') as month,
                        COUNT(*) as total,
                        SUM(CASE WHEN status = 'approved' THEN 1 ELSE 0 END) as approved,
                        SUM(CASE WHEN status = 'rejected' THEN 1 ELSE 0 END) as rejected,
                        SUM(CASE WHEN status = 'pending' THEN 1 ELSE 0 END) as pending,
                        SUM(CASE WHEN suspicious_flag = TRUE THEN 1 ELSE 0 END) as suspicious
                    FROM leaves
                    WHERE applied_at >= DATE_SUB(NOW(), INTERVAL 6 MONTH)
                    GROUP BY DATE_FORMAT(applied_at, '%Y-%m')
                    ORDER BY month DESC
                """)
                
                return cursor.fetchall()
        except Exception as e:
            print(f"Error getting monthly summary: {e}")
            return []
        finally:
            if connection:
                connection.close()
    
    @staticmethod
    def get_user_activity_stats():
        """Get user activity statistics"""
        db = Database()
        connection = db.get_connection()
        try:
            if not connection:
                return {}
            
            with connection.cursor() as cursor:
                stats = {}
                
                # Basic counts
                cursor.execute("SELECT COUNT(*) as count FROM students")
                stats['total_students'] = cursor.fetchone()['count']
                
                cursor.execute("SELECT COUNT(*) as count FROM proctors")
                stats['total_proctors'] = cursor.fetchone()['count']
                
                cursor.execute("SELECT COUNT(*) as count FROM hostel_supervisors")
                stats['total_supervisors'] = cursor.fetchone()['count']
                
                # Active users (last 30 days)
                cursor.execute("""
                    SELECT COUNT(DISTINCT student_reg) as count 
                    FROM leaves 
                    WHERE applied_at >= DATE_SUB(NOW(), INTERVAL 30 DAY)
                """)
                stats['active_students'] = cursor.fetchone()['count']
                
                # Average leaves per student
                cursor.execute("""
                    SELECT AVG(leave_count) as avg_count 
                    FROM (
                        SELECT student_reg, COUNT(*) as leave_count 
                        FROM leaves 
                        GROUP BY student_reg
                    ) as student_leaves
                """)
                avg_result = cursor.fetchone()
                stats['avg_leaves_per_student'] = avg_result['avg_count'] or 0 if avg_result else 0
                
                # Most active proctor
                cursor.execute("""
                    SELECT p.name, COUNT(l.leave_id) as leave_count
                    FROM leaves l
                    JOIN proctors p ON l.proctor_id = p.employee_id
                    GROUP BY l.proctor_id
                    ORDER BY leave_count DESC
                    LIMIT 1
                """)
                most_active = cursor.fetchone()
                stats['most_active_proctor'] = f"{most_active['name']} ({most_active['leave_count']} leaves)" if most_active else "N/A"
                
                # Most active hostel block
                cursor.execute("""
                    SELECT s.hostel_block, COUNT(l.leave_id) as leave_count
                    FROM leaves l
                    JOIN students s ON l.student_reg = s.reg_number
                    GROUP BY s.hostel_block
                    ORDER BY leave_count DESC
                    LIMIT 1
                """)
                most_active_block = cursor.fetchone()
                stats['most_active_block'] = f"{most_active_block['hostel_block']} ({most_active_block['leave_count']} leaves)" if most_active_block else "N/A"
                
                return stats
        except Exception as e:
            print(f"Error getting user activity stats: {e}")
            traceback.print_exc()
            return {}
        finally:
            if connection:
                connection.close()